export const projects = [
  {
    title: 'Voice Powered Expense Tracker',
    description: "Developed a webapp using Html,Css,React,Context api,speechly that helps to keep accurate record of your money inflow and outflow. In this user can add or remove expenses manually or using voice assistant(using speechly api) . Their will be a complete track of inflow and outflow of expense in form of pie chart. The pie charts will automatically get updated after adding and removing of Expenses.",
    image: '/images/1.jpg',
      tags: ['React', 'Speechly'],
    source: 'https://amazing-turing-663bc0.netlify.app/',
    visit: 'https://github.com/tss004/Voice-Powered-Expense-Tracker',
    count: 0,
    id: 0,
  },
  {
    title: 'Get Connected',
    description:"Developed a webapp using html,css,Nodejs,Expressjs,socket.io which allow mutiple user to join mutiple chat rooms. It allows mutiple user be able to chat with each other instantly. App updates all user whenever any user logs in or logs out and also track of login and logout time.",
    image: '/images/2.png',
    tags: ['HTML', 'CSS','Nodejs','Expressjs'],
    source: 'https://chat-app-tss.herokuapp.com/',
    visit: 'https://github.com/tss004/Chat-Application',
    count: 0,
    id: 1,
  },
  {
    title: 'Cryptocurrency-Tracker',
    description:"Created a web application using Reactjs and coingecko api that enables you as an user to keep track of the ever-changing value of your different coins so that you can manage your portfolio properly. User can get weekly ,monthly ,yearly statistics in form of graphical representation",
    image: '/images/7.png',
    tags: ['Reactjs'],
    source: 'https://practical-spence-cbcde1.netlify.app/',
    visit: 'https://github.com/tss004/Cryptocurrency-Tracker',
    count: 0,
    id: 1,
  },
  {
    title: 'Blog App',
    description: "Created a webapp using nodejs,expressjs,ejs,mangodb.It is a informational website displaying information in reverse chronological order, with the latest posts appearing first, at the top.It is a platform where user can create,edit,read,delete the blogs and share their views on an individual subject.",
      image: '/images/3.png',
      tags: ['Nodejs', 'Expressjs','EJS','MongoDB'],
    source: '',
    visit: 'https://github.com/tss004/Blog-app',
    count: 1,
    id: 2,
  },
  {
    title: 'Digital Billing and Invoices system',
    description: "It is a software made using python and tkinter that helps to generates billing for rendered services and products. This software helps to add products and also creates a list of services and products along with their corresponding costs and sends an email to customers as an invoice. Admin can also add or remove the products through software.",
    image: '/images/4.png',
    tags: ['Python', 'Tkinter'],
    source: '',
    visit: 'https://github.com/tss004/Digital-Billing-and-Invoices-system',
    count: 1,
    id: 3,
  },
  {
    title: 'Bank Record System',
    description: "This application allows operation like create account, deposit/withdraw amount, balance enquiry, modify account. It also provide functionality to close account permanently, display all account holder list using cpp.",
    image: '/images/6.png',
    tags: ['C++'],
    source: '',
    visit: 'https://github.com/tss004/Bank-Record-system',
    count: 1,
    id: 3,
  },
];

export const Judgesid = [
  {
    title: 'Github',
    description: '',
    image: '',
    tags: [],
    visit: 'https://github.com/tss004',
    source: '',
    id: 3,
  },
  {
    title: 'Hackerrank',
    description: '',
    image: '',
    tags: [],
    visit: 'https://www.hackerrank.com/santtanay',
    source: '',
    id: 3,
  },
  {
    title: 'Leetcode',
    description: '',
    image: '',
    tags: [],
    visit: 'https://leetcode.com/far_racer/',
    source: '',
    id: 3,
  },
  {
    
    title: 'Geeksforgeeks',
    description: '',
    image: '',
    tags: [],
    visit: 'https://auth.geeksforgeeks.org/user/tanaysant17/practice/',
    source: '',
    id: 3,
  },
  
  
]